//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smirnov_Georgii_PCS_304_Sessiya1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ses1Entities : DbContext
    {
        private static Ses1Entities _context;
        public Ses1Entities()
        : base("name=Ses1Entities")
        {
        }
        public static Ses1Entities GetContext()
        {
            if (_context == null)
                _context = new Ses1Entities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Pavilions> Pavilions { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
        public virtual DbSet<Shop_Centers> Shop_Centers { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
    
        public virtual int Number1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Number1");
        }
    
        public virtual ObjectResult<Rent2_Result> Rent2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rent2_Result>("Rent2");
        }
    
        public virtual int rentPavilion(Nullable<int> idTanant, Nullable<int> idEmployee, string pavilion_Number, string statusPavilion, Nullable<System.DateTime> start_rent, Nullable<System.DateTime> end_rent, Nullable<int> sC_ID)
        {
            var idTanantParameter = idTanant.HasValue ?
                new ObjectParameter("idTanant", idTanant) :
                new ObjectParameter("idTanant", typeof(int));
    
            var idEmployeeParameter = idEmployee.HasValue ?
                new ObjectParameter("idEmployee", idEmployee) :
                new ObjectParameter("idEmployee", typeof(int));
    
            var pavilion_NumberParameter = pavilion_Number != null ?
                new ObjectParameter("Pavilion_Number", pavilion_Number) :
                new ObjectParameter("Pavilion_Number", typeof(string));
    
            var statusPavilionParameter = statusPavilion != null ?
                new ObjectParameter("statusPavilion", statusPavilion) :
                new ObjectParameter("statusPavilion", typeof(string));
    
            var start_rentParameter = start_rent.HasValue ?
                new ObjectParameter("start_rent", start_rent) :
                new ObjectParameter("start_rent", typeof(System.DateTime));
    
            var end_rentParameter = end_rent.HasValue ?
                new ObjectParameter("end_rent", end_rent) :
                new ObjectParameter("end_rent", typeof(System.DateTime));
    
            var sC_IDParameter = sC_ID.HasValue ?
                new ObjectParameter("SC_ID", sC_ID) :
                new ObjectParameter("SC_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rentPavilion", idTanantParameter, idEmployeeParameter, pavilion_NumberParameter, statusPavilionParameter, start_rentParameter, end_rentParameter, sC_IDParameter);
        }
    
        public virtual int RentPr(Nullable<int> tent_ID, Nullable<int> empl_ID, Nullable<int> sC_ID, string pV_ID, Nullable<System.DateTime> rental_Start, Nullable<System.DateTime> rental_End)
        {
            var tent_IDParameter = tent_ID.HasValue ?
                new ObjectParameter("Tent_ID", tent_ID) :
                new ObjectParameter("Tent_ID", typeof(int));
    
            var empl_IDParameter = empl_ID.HasValue ?
                new ObjectParameter("Empl_ID", empl_ID) :
                new ObjectParameter("Empl_ID", typeof(int));
    
            var sC_IDParameter = sC_ID.HasValue ?
                new ObjectParameter("SC_ID", sC_ID) :
                new ObjectParameter("SC_ID", typeof(int));
    
            var pV_IDParameter = pV_ID != null ?
                new ObjectParameter("PV_ID", pV_ID) :
                new ObjectParameter("PV_ID", typeof(string));
    
            var rental_StartParameter = rental_Start.HasValue ?
                new ObjectParameter("Rental_Start", rental_Start) :
                new ObjectParameter("Rental_Start", typeof(System.DateTime));
    
            var rental_EndParameter = rental_End.HasValue ?
                new ObjectParameter("Rental_End", rental_End) :
                new ObjectParameter("Rental_End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RentPr", tent_IDParameter, empl_IDParameter, sC_IDParameter, pV_IDParameter, rental_StartParameter, rental_EndParameter);
        }
    }
}
