//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smirnov_Georgii_PCS_304_Sessiya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.Rental = new HashSet<Rental>();
        }
    
        public string Pavilion_Number { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Status { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<double> Price_M2 { get; set; }
        public Nullable<double> Value_Adder_Factor { get; set; }
        public int SC_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rental { get; set; }
        public virtual Shop_Centers Shop_Centers { get; set; }
    }
}
