//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smirnov_Georgii_PCS_304_Sessiya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Rental_ID { get; set; }
        public Nullable<int> Tenant_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Pavilion_Number { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Rental_Start { get; set; }
        public Nullable<System.DateTime> Rental_End { get; set; }
        public Nullable<int> SC_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
