//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smirnov_Georgii_PCS_304_Sessiya1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Centers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_Centers()
        {
            this.Pavilions = new HashSet<Pavilions>();
        }
    
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Number_Of_Pawilion { get; set; }
        public string Sity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> Value_Adder_Factor { get; set; }
        public Nullable<int> Floor { get; set; }
        public int SC_ID { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilions> Pavilions { get; set; }
    }
}
